logging:
  level: INFO
  stdout:
    enabled: true
  file:
    enabled: true
    path: /Users/cciollaro/hotplots.log

source:
  # How often to check for new available actions (new plots or transfers completed)
  check_source_drives_sleep_seconds: 60

  # If you have multiple source drives, the method for prioritizing which plot to start transferring will be
  # as follows:
  # plot_with_oldest_timestamp: selects the plot file with the oldest timestamp across all source drives
  # drive_with_least_space_remaining: take plot from the source drive with the least available space (after active transfers)
  # drive_with_lowest_percent_space_remaining: take plot from the source drive with the least remaining percent of space (after active transfers)
  # config_order: prefer to take plots from the drive as they're listed in config order
  # random: select the next plot randomly
  selection_strategy: plot_with_oldest_timestamp

  drives:
  - path: /Users/cciollaro/hotplots-dir
    max_concurrent_outbound_transfers: 2

targets:
  # Possible values are:
  # local - prefer transferring to an eligible local drive, even over a more optimal eligible remote drive
  # remote - prefer transferring to an eligible remote drive, even over a more optimal eligible local drive
  # unbiased - prefer the optimal eligible drive, regardless of local or remote.
  # Default: local. Generally will have less IO overhead so is a sane default.
  target_host_preference: local

  # The drive to write to can be prioritized in the following ways:
  # config_order: prefer eligible drives in the order they appear in this config file. local block will take priority.
  # drive_with_least_space_remaining: put the plot on the drive with least remaining space (after active transfers)
  # drive_with_lowest_percent_space_remaining: put the plot in the dirve with the least remaining percent (after active transfers)
  # drive_with_most_space_remaining: take plot from
  # drive_with_highest_percent_space_remaining:
  # random: select randomly
  selection_strategy: drive_with_most_space_remaining

  # Local drives are SATA or USB drives attached directly to your plotter.
  # Transfers are generally going to be faster and less bottle-necked than remote transfers
  # since they don't go over the network.
  local:
    drives:
      # The path doesn't need to be the mount point of the drive, but it is assumed to be the only path on the drive.
      - path: /Users/cciollaro/hotplots-dir
        # For most drives, a single plot transfer is probably going to saturate the write capacity (be it disk speed,
        # SATA speed, or USB speed). Therefore, the default value of 1 is probably what you want.
        # Note: if you share this drive as a target with other plotters (i.e. it's registered as a remote drive
        # for another instance of hotplots) then your limit is shared with the other plotters.
        max_concurrent_inbound_transfers: 1
        plot_replacement:
          enabled: true
          type: time-before
          value: "2021-06-01"

  remote:
    # How many outbound remote transfers this device is allowed to make. If a single outbound transfer already
    # saturates your network bandwidth then there should be no reason to raise this.
    max_concurrent_outbound_transfers: 1

    hosts:
      - hostname: thinkcentre.local
        username: cc
        port: 22
        # Note: This limit is globally, from all plotting machines.
        max_concurrent_inbound_transfers: 4

        drives:
          - path: /media/cc/easystore-12tb-1/chia-plots/
            # Note: This limit is globally, from all plotting machines that are running `hotplots`.
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              # possible values: timestamp-before, pool-key, farmer-key, k-size
              type: timestamp-before
              value: "2021-06-01"

          - path: /media/cc/easystore-12tb-2/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-14tb-1/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-14tb-2/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-14tb-3/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-1/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-2/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-3/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-4/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-5/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/elements-12tb-1/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/elements-12tb-2/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/elements-12tb-4/chia-plots/
            max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"
