logging:
  level: INFO

  stdout:
    enabled: true
  file:
    enabled: true
    path: /Users/cciollaro/hotplots.log

sleep: 59

max_concurrent_transfers: 2

source_directories:
  - /mnt/hdd1000/chia-plots/

destinations:
  remote:
    - hostname: thinkcentre.local
      username: cc
      port: 22
      directories:
        - /media/cc/easystore-12tb-1/chia-plots/
        - /media/cc/easystore-12tb-2/chia-plots/
        - /media/cc/easystore-14tb-1/chia-plots/
        - /media/cc/easystore-14tb-2/chia-plots/
        - /media/cc/easystore-14tb-3/chia-plots/
        - /media/cc/easystore-16tb-1/chia-plots/
        - /media/cc/easystore-16tb-2/chia-plots/
        - /media/cc/easystore-16tb-3/chia-plots/
        - /media/cc/easystore-16tb-4/chia-plots/
        - /media/cc/easystore-16tb-5/chia-plots/
        - /media/cc/elements-12tb-1/chia-plots/
        - /media/cc/elements-12tb-2/chia-plots/
        - /media/cc/elements-12tb-4/chia-plots/
  local:
    - /Users/cciollaro/PycharmProjects/hotplots/testdir_destination/