logging:
  level: INFO
  stdout:
    enabled: true
  file:
    enabled: true
    path: /Users/cciollaro/hotplots.log

source:
  # How often to check for new available actions (new plots or transfers completed)
  check_source_drives_sleep_seconds: 60

  # least_available_space: take plot from the source drive with the least available space (after active transfers)
  # random: select the next plot randomly
  selection_strategy: least_available_space

  drives:
  - path: /Users/cciollaro/hotplots-dir
    drive_max_concurrent_outbound_transfers: 1

targets:
  # Always prefer a local transfer instead of a remote one
  prefer_local_target: true
  global_max_concurrent_outbound_transfers: 4

  local:
    host_max_concurrent_inbound_transfers: 4
    drives:
      - path: /Users/cciollaro/hotplots-dir
        drive_max_concurrent_inbound_transfers: 1
        plot_replacement:
          enabled: true
          type: time-before
          value: "2021-06-01"

  remote:
    max_concurrent_remote_transfers: 2

    hosts:
      - hostname: thinkcentre.local
        username: cc
        port: 22
        host_max_concurrent_inbound_transfers: 4
        drives:
          - path: /media/cc/easystore-12tb-1/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              # possible values: timestamp-before, pool-key, farmer-key, k-size
              type: timestamp-before
              value: "2021-06-01"

          - path: /media/cc/easystore-12tb-2/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-14tb-1/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-14tb-2/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-14tb-3/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-1/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-2/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-3/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-4/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/easystore-16tb-5/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/elements-12tb-1/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/elements-12tb-2/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"

          - path: /media/cc/elements-12tb-4/chia-plots/
            drive_max_concurrent_inbound_transfers: 1
            plot_replacement:
              enabled: true
              type: time-before
              value: "2021-06-01"
