# Directories which you will watch on your local machine
source_directories:
  - /mnt/hdd1000/chia-plots/

destinations:
  # Remote destinations
  remote:
    - hostname: thinkcentre.local
      username: cc
      port: 22
      directories:
        - /media/cc/easystore-12tb-1/chia-plots/
        - /media/cc/easystore-12tb-2/chia-plots/
        - /media/cc/easystore-14tb-1/chia-plots/
        - /media/cc/easystore-14tb-2/chia-plots/
        - /media/cc/easystore-14tb-3/chia-plots/
        - /media/cc/easystore-16tb-1/chia-plots/
        - /media/cc/easystore-16tb-2/chia-plots/
        - /media/cc/easystore-16tb-3/chia-plots/
        - /media/cc/easystore-16tb-4/chia-plots/
        - /media/cc/easystore-16tb-5/chia-plots/
        - /media/cc/elements-12tb-1/chia-plots/
        - /media/cc/elements-12tb-2/chia-plots/
        - /media/cc/elements-12tb-4/chia-plots/
# Directories on your local machine
#  local:
#    - /Users/cciollaro/PycharmProjects/hotplots/testdir_destination/